### ISSUE TITLE
cannot reproduce example code

### ISSUE THREAD

**Issue by JuHey** [brunobeltran/pscan#1]
Hi,

I cannot seem to reproduce the example code. For some reasons I get a 'TypeError': "module object does not support item assigned.
<img width="692" alt="image" src="https://user-images.githubusercontent.com/36309128/55808331-e2113300-5ab1-11e9-8b8d-7e03184f0155.png">
 
Here is the code I ran from jupyter lab:
<img width="508" alt="image" src="https://user-images.githubusercontent.com/36309128/55808779-c2c6d580-5ab2-11e9-8508-cddc0ad3f88b.png">

pscan installed via: pip3 install pscan
It must be something trivial but I cannot see it...

**Comment by brunobeltran** [comment]
Hi JuHey, sorry for late reply. 

I'm not sure how you manage to get a TypeError there. Whenever I run that same code, I get a "NameError: name 'p' is not defined". 

Can you confirm that you initialized `p = {}` at some point?

**Comment by JuHey** [comment]
Hi brunobeltran,

No worries. I did not initialize p = {}. That might be just it. I will try it tonight.

Best,

Jurgen

**Comment by brunobeltran** [comment]
I think you were right that the README was previously incorrect, but it appears to be fixed now, thanks!
